/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://5bbqsexxyjd6jb3zfl5hfxmc7i.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kcqf4gn2gng5ncwjk7ekxlp42q",
    "aws_cognito_identity_pool_id": "eu-central-1:d9b79629-d014-4ede-ae7c-c5bbe56f1cb5",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_j4MYrjJV0",
    "aws_user_pools_web_client_id": "2gm49f1j8j8br1p0n7ct7klep3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
